version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.dev
  docker_test:
    container_name: poetry_test
    image: library/python:3.9
    build: ./sandbox
    volumes:
    - ./sandbox:/subvolume
