version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env.dev

  docker_test:
    image: poetry-test
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env.dev
    environment:
      - POSTGRES_HOST=postgres-db
    command: tail -f /dev/null
